kittygram/models.py
from flask import render_template, current_app
from datetime import  datetime
from flask_login import UserMixin
from kittygram import db
from . import login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    img_filename = db.Column(db.String(50))
    text = db.Column(db.String(50))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow) # TODO: add time from now system
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    likes = db.relationship('Like')

    def to_json(self):
        json_post = {
            'id': self.id,
            'img_filename': self.img_filename,
            'text': self.text,
            'author_id': self.author_id,
            'html': render_template('post.html', post=self, author=User.query.filter_by(id=self.author_id).first())
        }
        return json_post

class Like(db.Model):
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'), primary_key=True)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True)
    email = db.Column(db.String(64), unique=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    nickname = db.Column(db.String(64), default=False)
    posts = db.relationship("Post", backref='author')
    likes = db.relationship("Like")

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)


    def check_password(self, password):
        if check_password_hash(self.password_hash, password):
            return True

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
    
        if data['confirm'] != self.id:
            return False
        
        self.confirmed = True
        db.session.merge(self)
        db.session.commit()
        return True
        

kittygram/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bootstrap import Bootstrap4
from flask_mail import Mail
from config import Config

mail = Mail()
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
bootstrap = Bootstrap4()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    mail.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    from kittygram.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from kittygram.main import main as main_bp
    app.register_blueprint(main_bp)

    return app

from kittygram import models

kittygram/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from kittygram.main import routes

kittygram/main/routes.py
from math import floor
from pickletools import optimize
from re import I
from turtle import pos
from flask import get_flashed_messages, redirect, jsonify,render_template, abort, flash
from sqlalchemy import desc
from werkzeug.utils import secure_filename
from pathlib import Path
from PIL import Image

from . import main
from kittygram.models import Post, User, Like
from kittygram import db

from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length
import os
import datetime


UPLOAD_FOLDER = os.path.abspath(os.getcwd()) + '/kittygram/static/images'

class PostForm(FlaskForm):
    file = FileField('', description='Please upload a photo of your cat.',validators=[FileRequired(), FileAllowed(['jpg', 'png'], 'Please upload an image')])
    text = StringField('', description='Tell people something about your cutie!', validators=[DataRequired(), Length(5,50, 'Text must have between 5 and 50 characters.')] )
    submit = SubmitField('Upload')

@main.route('/')
def index():
    return render_template('home.html')

@login_required
@main.route('/upload', methods = ['GET', 'POST'])
def upload():
    form = PostForm()
    if form.validate_on_submit():
        f = form.file.data
        
        filename = secure_filename(f.filename) # remove file path for security 
        filename = make_unique(filename) # replace name by unique ID
        
        # resize if necessary
        f = Image.open(f)
        w = f.size[0]
        h = f.size[1]

        MAX_SIZE = 700
        if w > MAX_SIZE:
            resize_factor = w / MAX_SIZE
            w = floor(w / resize_factor)
            h = floor(h / resize_factor)
        elif h > MAX_SIZE:
            resize_factor = h/MAX_SIZE
            w = floor(w / resize_factor)
            h = floor(h / resize_factor)
        f = f.resize((w,h))
        
        f.save(UPLOAD_FOLDER + '/' + filename) 

        post = Post(img_filename=filename, text=form.data['text'], author_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect('/')
    return render_template('upload.html', form=form)

# TODO: add delete post endpoint

@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    
    print(user.posts)
    return render_template('user.html', user=user)

@main.route('/posts')
def get_posts():
    posts = Post.query.all()
    return jsonify({'posts': [post.to_json() for post in posts]})

@main.route('/posts/<username>')
def get_posts_by_username(username):
    author = User.query.filter_by(username = username).first()
    posts = Post.query.filter_by(author_id = author.id)
    return jsonify({'posts': [post.to_json() for post in posts]})

@main.route('/like/<post_id>', methods=['POST'])
def like(post_id):
    like_query = Like.query.filter(Like.author_id == current_user.id, Like.post_id == post_id)
    like_count = len(Post.query.filter_by(id = post_id).first().likes)
    if like_query.first():

        like_query.delete()
        db.session.commit()

        response = jsonify({'success': False, 'likeCount': like_count - 1})
        return response
    else:
        like = Like(author_id = current_user.id, post_id = post_id)
        db.session.add(like)
        db.session.commit()
        
        response = jsonify({'success': True, 'likeCount': like_count + 1})
        response.status_code = 200
        return response

from uuid import uuid4
def make_unique(string):
    ident = uuid4().__str__()
    return f'{ident}{Path(string).suffix}'

kittygram/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
            {% endblock %}
            <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">

        <title>Kittygram</title>
        {% endblock %}
    </head>
    <body>
        <!-- Your page content -->
        <nav id="navbar" class="navbar navbar-dark navbar-expand-md justify-content-center" style="background-color: #6b4b3e;">
            <a href="/" class="navbar-brand d-flex w-50 mr-auto" ><div style="font-size:xx-large">Kittygram</div> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ current_user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="color: black !important;">
                            <a class="dropdown-item" href="/user/{{ current_user.username }}">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('auth.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('auth.register')}}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="main">
            {% block content %}
            
            {% endblock %}
            {% with messages=get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}
                <br>
                <div class="alert alert-warning">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        {% block scripts %}
            <!-- Optional JavaScript -->
            <script src="../static/jquery.min.js"></script>
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

kittygram/templates/home.html
{% extends 'base.html' %}
{% block content %}
<title>Kittygram</title>
{% if current_user.is_authenticated %}
<p> <!-- TODO: move this to navbar and add profile button -->
    {% if not current_user.confirmed %}
    <b>We have sent you an email. Please confirm your account.</b>
    {% endif %}
</p>
{% endif %}

{% if current_user.is_authenticated %}
<a class="btn btn-warning btn-lg" role="button" href="{{ url_for('main.upload')}}">Upload</a>
{% endif %}

<h1>Posts</h1>

<div id="posts">    
</div>

<script src="../static/jquery.min.js"></script>
<script type="module" src="../static/home.js"></script>
{% endblock %}

kittygram/templates/post.html
<div class="post-container card border-primary mb-3" data-post-id="{{ post.id }}" style="width: 25rem;">
    <div class="card-header">
        <b>{{ author.username }}</b>
    </div>
    <img src="/static/images/{{ post.img_filename }}" class="card-img-top" style="max-height: 30rem; object-fit: contain;">
    <div class="card-body">
        <h3 class="card-title">{{ post.text }}</h3>
        <p class="card-text"><small class="text-muted">{{ post.timestamp.strftime("%A, %d. %B %Y %I:%M%p") }}</small></p>
        <button type="button" class="like-btn btn btn-danger">
            Like <span class="like-count badge badge-light">0</span>
        </button>
    </div>
</div>

kittygram/templates/upload.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block content %}
<h1>Upload</h1>
    {{ render_form(form)}}
{% endblock %}

kittygram/templates/user.html
{% extends 'base.html' %}

{% block content %}
<div class='page-header'>
    <h1>{{ user.username }}</h1>
    {% if user == current_user %}
    <a class="btn btn-default">Edit profile</a>
    {% endif %}
</div>
<div id="posts">
    
</div>

<script src="../static/jquery.min.js"></script>
<script type="module" src="../static/user.js"></script>
{% endblock %}